import MirageJs from 'miragejs';

import {PaginationResult} from '@/app/components/PaginationTable/types';
import {MASS_UPLOAD_STATUS, UploadDTO, UploadTypes} from '@/app/modules/mass-upload/types';
import {
    PO_STATUS,
    PO_TYPE,
    PurchaseOrderDTO,
    PurchaseOrderItemDTO,
    PurchaseOrderItemLocationListDTO,
    PurchaseOrderListDTO,
} from '@/app/modules/purchase-orders/types';
import {NO_DATA} from '@/libs/text';
import {AccountDTO, ROLES, UserDTO} from '@/store/account/types';

export const mockAccount: AccountDTO = {
    user: {
        id: 8008135,
        first_name: 'Alex',
        last_name: 'M',
        email: 'mail@example.com',
        role: ROLES.ADMIN,
    },
    access_token: '0000-0000',
    refresh_token: '0000-0000',
};

export const MOCK_EMAIL = 'vanilla@landmark.com';
export const MOCK_PASSWORD = '12345678';

export const mockUsers: Array<UserDTO> = [
    {id: 1, email: 'john.doe@example.com', first_name: 'John', last_name: 'Doe', role: ROLES.ADMIN},
    {id: 2, email: 'jane.smith@example.com', first_name: 'Jane', last_name: 'Smith', role: ROLES.OBSERVER},
    {id: 3, email: 'michael.johnson@example.com', first_name: 'Michael', last_name: 'Johnson', role: ROLES.OPERATOR},
    {id: 4, email: 'emily.davis@example.com', first_name: 'Emily', last_name: 'Davis', role: ROLES.SECURITY_ADMIN},
    {id: 5, email: 'david.miller@example.com', first_name: 'David', last_name: 'Miller', role: ROLES.ADMIN},
    {id: 6, email: 'olivia.wilson@example.com', first_name: 'Olivia', last_name: 'Wilson', role: ROLES.OBSERVER},
    {id: 7, email: 'daniel.anderson@example.com', first_name: 'Daniel', last_name: 'Anderson', role: ROLES.OPERATOR},
    {
        id: 8,
        email: 'matthew.taylor@example.com',
        first_name: 'Matthew',
        last_name: 'Taylor',
        role: ROLES.SECURITY_ADMIN,
    },
    {id: 9, email: 'sarah.brown@example.com', first_name: 'Sarah', last_name: 'Brown', role: ROLES.ADMIN},
    {id: 10, email: 'james.nelson@example.com', first_name: 'James', last_name: 'Nelson', role: ROLES.OBSERVER},
];
export const mockPOList = (request: MirageJs.Request): PaginationResult<Partial<PurchaseOrderListDTO>> => ({
    content: [
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocationId: 15,
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
            group: 'group',
            importId: 15,
            importOrderInd: 15,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocationId: 15,
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.CLOSED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importerBillToLoc: 5215,
            importBillToLocType: '-',
            payMethod: 'MINT',
            poType: PO_TYPE.IMPORT,
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrderId: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discountOff: 3,
            markupPercentRetail: 3,
            totalOrderRetailExclVAT: 33,
            totalOrderRetailInclVAT: 33,
            totalVAT: 333,
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

export const mockPOItem: PurchaseOrderItemDTO = {
    id: 7165256,
    supplierName: 'Rose inc.',
    orderType: 'N/B',
    totalQuantity: 100,
    status: PO_STATUS.APPROVED,
    isPack: true,
};

export const mockPOView: Partial<PurchaseOrderDTO> = {
    id: 1234333,
    orderType: NO_DATA,
    importer: 1, // или объект ImporterDTO
    includeOnOrder: 'No',
    importOrder: 'Yes',
    estimatedRDCInStock: '2024-11-25T00:00:00.000Z',
    discount: 3,
    primaryCurrency: 'AED',
    totalOrderCost: null, // пока пусто, можно задать значения позже
    canceledCost: null, // пока пусто
    exchangeRate: 0.27,
    contact: '647584736',
    ediPO: 'No',
    status: PO_STATUS.APPROVED,
    qcRequired: 'Yes',
    latestShipmentDate: '2024-12-15T00:00:00.000Z',
    supplierCode: 1425367, // или объект SupplierDTO
    supplierName: 'Rose Inc.',
    supplierSiteId: 1425367,
    otbEndOfWeekDate: '2024-12-27T00:00:00.000Z',
    orderNo: 123456,
    landedCost: 2000,
    orderCurrency: 'AED, USD',
    notAfterDate: '2024-12-31T00:00:00.000Z',
    notBeforeDate: '2024-11-01T00:00:00.000Z',
    importCountry: 'China',
    outstandingCost: 1500,
    locationPickUp: 'WH1',
    earliestShipDate: '2024-11-25T00:00:00.000Z',
    vendorOrderId: 1234333,
    paymentTermsName: 'Net 30 Days',
    orderApprovalDate: '2024-11-24T00:00:00.000Z',
    location:
        'Shanghai Special Administrative Region "Penghai," Industrial Harbor Nantan, Plot No. 732, Huangpu River Coastal Strip, Berth 19, Longjiang Port Complex',
    poType: PO_TYPE.IMPORT,
    expenses: 50.0,
};

export const mockOrderItemsLocationsList = (
    request: MirageJs.Request,
): PaginationResult<PurchaseOrderItemLocationListDTO> => ({
    content: [
        {
            id: 12345213,
            item: 'Item1',
            totalItemQuantity: 100,
            itemDescription: 'Description for Item 1',
            countryOfSourcing: 'Country A',
            costSource: 'Supplier A',
            location: 1,
            locationType: 'Warehouse',
            locationName: 'Main Warehouse',
            unitOfPurchase: 'pcs',
            quantity: 50,
            variance: '0.00',
            currency: 'USD',
            estimatedInStockDate: '2024-11-01',
            itemType: 'Type A',
            itemParent: 'Parent A',
            itemGrandparent: 'Grandparent A',
            color: 'Red',
            style: 'Casual',
            size: 'M',
            detailedColorDescription: 'Bright Red',
            localCurrency: 'USD',
            nonScaling: 'No',
            unitCostUop: 1000,
            supplierUnitCost: 950,
            unitElcUop: '1200',
            totalElcUop: '12000',
            vpn: 'VPN12345',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-10-15',
            earliestShipmentDate: '2024-10-01',
        },
        {
            id: 12345213,
            item: 'Item2',
            totalItemQuantity: 200,
            itemDescription: 'Description for Item 2',
            countryOfSourcing: 'Country B',
            costSource: 'Supplier B',
            location: 2,
            locationType: 'Store',
            locationName: 'Store Front',
            unitOfPurchase: 'boxes',
            quantity: 20,
            variance: '5.00',
            currency: 'EUR',
            estimatedInStockDate: '2024-11-15',
            itemType: 'Type B',
            itemParent: 'Parent B',
            itemGrandparent: 'Grandparent B',
            color: 'Blue',
            style: 'Formal',
            size: 'L',
            detailedColorDescription: 'Navy Blue',
            localCurrency: 'EUR',
            nonScaling: 'Yes',
            unitCostUop: 500,
            supplierUnitCost: 475,
            unitElcUop: '600',
            totalElcUop: '12000',
            vpn: 'VPN67890',
            cancelledQtyUop: '1',
            latestShipmentDate: '2024-10-25',
            earliestShipmentDate: '2024-10-10',
        },
        {
            id: 12345213,
            item: 'Item3',
            totalItemQuantity: 300,
            itemDescription: 'Description for Item 3',
            countryOfSourcing: 'Country C',
            costSource: 'Supplier C',
            location: 3,
            locationType: 'Warehouse',
            locationName: 'Secondary Warehouse',
            unitOfPurchase: 'packs',
            quantity: 80,
            variance: '10.00',
            currency: 'GBP',
            estimatedInStockDate: '2024-11-10',
            itemType: 'Type C',
            itemParent: 'Parent C',
            itemGrandparent: 'Grandparent C',
            color: 'Green',
            style: 'Sport',
            size: 'S',
            detailedColorDescription: 'Forest Green',
            localCurrency: 'GBP',
            nonScaling: 'No',
            unitCostUop: 350,
            supplierUnitCost: 330,
            unitElcUop: '400',
            totalElcUop: '32000',
            vpn: 'VPN54321',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-10-20',
            earliestShipmentDate: '2024-10-05',
        },
        {
            id: 12345213,
            item: 'Item4',
            totalItemQuantity: 150,
            itemDescription: 'Description for Item 4',
            countryOfSourcing: 'Country D',
            costSource: 'Supplier D',
            location: 4,
            locationType: 'Store',
            locationName: 'Downtown Store',
            unitOfPurchase: 'units',
            quantity: 75,
            variance: '0.00',
            currency: 'USD',
            estimatedInStockDate: '2024-11-05',
            itemType: 'Type D',
            itemParent: 'Parent D',
            itemGrandparent: 'Grandparent D',
            color: 'Yellow',
            style: 'Outdoor',
            size: 'M',
            detailedColorDescription: 'Bright Yellow',
            localCurrency: 'USD',
            nonScaling: 'Yes',
            unitCostUop: 200,
            supplierUnitCost: 190,
            unitElcUop: '250',
            totalElcUop: '37500',
            vpn: 'VPN11111',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-10-10',
            earliestShipmentDate: '2024-10-01',
        },
        {
            id: 12345213,
            item: 'Item5',
            totalItemQuantity: 80,
            itemDescription: 'Description for Item 5',
            countryOfSourcing: 'Country E',
            costSource: 'Supplier E',
            location: 5,
            locationType: 'Warehouse',
            locationName: 'Central Warehouse',
            unitOfPurchase: 'items',
            quantity: 40,
            variance: '2.00',
            currency: 'AUD',
            estimatedInStockDate: '2024-11-20',
            itemType: 'Type E',
            itemParent: 'Parent E',
            itemGrandparent: 'Grandparent E',
            color: 'Black',
            style: 'Casual',
            size: 'L',
            detailedColorDescription: 'Jet Black',
            localCurrency: 'AUD',
            nonScaling: 'No',
            unitCostUop: 150,
            supplierUnitCost: 145,
            unitElcUop: '180',
            totalElcUop: '7200',
            vpn: 'VPN22222',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-10-30',
            earliestShipmentDate: '2024-10-15',
        },
        {
            id: 12345213,
            item: 'Item6',
            totalItemQuantity: 225,
            itemDescription: 'Description for Item 6',
            countryOfSourcing: 'Country F',
            costSource: 'Supplier F',
            location: 6,
            locationType: 'Store',
            locationName: 'North Side Store',
            unitOfPurchase: 'pieces',
            quantity: 100,
            variance: '20.00',
            currency: 'CAD',
            estimatedInStockDate: '2024-11-30',
            itemType: 'Type F',
            itemParent: 'Parent F',
            itemGrandparent: 'Grandparent F',
            color: 'White',
            style: 'Formal',
            size: 'S',
            detailedColorDescription: 'Bright White',
            localCurrency: 'CAD',
            nonScaling: 'Yes',
            unitCostUop: 300,
            supplierUnitCost: 280,
            unitElcUop: '350',
            totalElcUop: '28000',
            vpn: 'VPN33333',
            cancelledQtyUop: '2',
            latestShipmentDate: '2024-10-28',
            earliestShipmentDate: '2024-10-12',
        },
        {
            id: 12345213,
            item: 'Item7',
            totalItemQuantity: 50,
            itemDescription: 'Description for Item 7',
            countryOfSourcing: 'Country G',
            costSource: 'Supplier G',
            location: 7,
            locationType: 'Warehouse',
            locationName: 'East Warehouse',
            unitOfPurchase: 'sets',
            quantity: 25,
            variance: '1.50',
            currency: 'JPY',
            estimatedInStockDate: '2024-12-01',
            itemType: 'Type G',
            itemParent: 'Parent G',
            itemGrandparent: 'Grandparent G',
            color: 'Purple',
            style: 'Sport',
            size: 'XL',
            detailedColorDescription: 'Dark Purple',
            localCurrency: 'JPY',
            nonScaling: 'No',
            unitCostUop: 4000,
            supplierUnitCost: 3900,
            unitElcUop: '4200',
            totalElcUop: '105000',
            vpn: 'VPN44444',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-11-01',
            earliestShipmentDate: '2024-10-15',
        },
        {
            id: 12345213,
            item: 'Item8',
            totalItemQuantity: 175,
            itemDescription: 'Description for Item 8',
            countryOfSourcing: 'Country H',
            costSource: 'Supplier H',
            location: 8,
            locationType: 'Store',
            locationName: 'West Side Store',
            unitOfPurchase: 'cases',
            quantity: 60,
            variance: '0.00',
            currency: 'CHF',
            estimatedInStockDate: '2024-11-25',
            itemType: 'Type H',
            itemParent: 'Parent H',
            itemGrandparent: 'Grandparent H',
            color: 'Pink',
            style: 'Casual',
            size: 'M',
            detailedColorDescription: 'Light Pink',
            localCurrency: 'CHF',
            nonScaling: 'Yes',
            unitCostUop: 550,
            supplierUnitCost: 500,
            unitElcUop: '600',
            totalElcUop: '105000',
            vpn: 'VPN55555',
            cancelledQtyUop: '0',
            latestShipmentDate: '2024-10-29',
            earliestShipmentDate: '2024-10-10',
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

const UPLOAD_TYPE_NAME = {
    [UploadTypes.PO_UPLOAD]: 'PO Upload',
};

export const uploadedFileResponse: UploadDTO = {
    id: 123412,
    vendorOrderId: '1421412',
    fileName: 'Table.csv',
    orderId: 6,
    createdBy: 'Daniil Babichev',
    uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
    uploaded: '2024-11-01T09:00:00',
    errors: [],
    status: MASS_UPLOAD_STATUS.UPLOADED,
};

export const mockMUList = (request: MirageJs.Request): PaginationResult<UploadDTO> => ({
    content: [
        {
            id: 1234333,
            vendorOrderId: 'BZ-1234567',
            fileName: 'Report1.csv',
            orderId: 123401,
            createdBy: 'Alice Johnson',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-01T09:00:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.WORKSHEET,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-2345678',
            fileName: 'Report2.csv',
            orderId: 123402,
            createdBy: 'Bob Smith',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-02T10:30:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.ERROR,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-3456789',
            fileName: 'Report3.csv',
            orderId: 123403,
            createdBy: 'Charlie Brown',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-03T11:45:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-4567890',
            fileName: 'Report4.csv',
            orderId: 123404,
            createdBy: 'Diana Prince',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-04T12:15:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.THREADED_AND_EXECUTING,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-5678901',
            fileName: 'Report5.csv',
            orderId: 123405,
            createdBy: 'Ethan Hunt',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-05T13:50:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-6789012',
            fileName: 'Report6.csv',
            orderId: 123406,
            createdBy: 'Fiona Gallagher',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-06T14:20:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-7890123',
            fileName: 'Report7.csv',
            orderId: 123407,
            createdBy: 'George Costanza',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-07T15:00:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.WORKSHEET,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-8901234',
            fileName: 'Report8.csv',
            orderId: 123408,
            createdBy: 'Hannah Montana',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-08T16:30:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.ERROR,
        },
        {
            id: 1234333,
            vendorOrderId: 'BZ-9012345',
            fileName: 'Report9.csv',
            orderId: 123409,
            createdBy: 'Ian Malcolm',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-09T17:45:00',
            errors: [],
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

export const mockMUView: UploadDTO = {
    id: 1234333,
    fileName: 'test.csv',
    orderId: 12345678,
    vendorOrderId: 'VENDOR123',
    uploadType: 'TYPE_A',
    createdBy: 'uploader1',
    uploaded: '2023-10-01T00:00:00Z',
    status: MASS_UPLOAD_STATUS.UPLOADED,
    errors: [
        {
            lineNumber: 1,
            columnName: 'COLUMN1',
            columnValue: 'VALUE1',
            errorMessage: 'Ошибка в значении',
        },
        {
            lineNumber: 2,
            columnName: 'COLUMN2',
            columnValue: 'VALUE2',
            errorMessage: 'Ошибка в значении',
        },
    ],
};
