import MirageJs from 'miragejs';

import {PaginationResult} from '@/app/components/PaginationTable/types';
import {MASS_UPLOAD_STATUS, UploadDTO, UploadTypes} from '@/app/modules/mass-upload/types';
import {
    PO_STATUS,
    PO_TYPE,
    PurchaseOrderDTO,
    PurchaseOrderItemDTO,
    PurchaseOrderListDTO,
} from '@/app/modules/purchase-orders/types';
import {NO_DATA} from '@/libs/text';
import {AccountDTO, ROLES, UserDTO} from '@/store/account/types';

export const mockAccount: AccountDTO = {
    user: {
        id: 8008135,
        first_name: 'Alex',
        last_name: 'M',
        email: 'mail@example.com',
        role: ROLES.ADMIN,
    },
    access_token: '0000-0000',
    refresh_token: '0000-0000',
};

export const mockUsers: Array<UserDTO> = [
    {id: 1, email: 'john.doe@example.com', first_name: 'John', last_name: 'Doe', role: ROLES.ADMIN},
    {id: 2, email: 'jane.smith@example.com', first_name: 'Jane', last_name: 'Smith', role: ROLES.OBSERVER},
    {id: 3, email: 'michael.johnson@example.com', first_name: 'Michael', last_name: 'Johnson', role: ROLES.OPERATOR},
    {id: 4, email: 'emily.davis@example.com', first_name: 'Emily', last_name: 'Davis', role: ROLES.SECURITY_ADMIN},
    {id: 5, email: 'david.miller@example.com', first_name: 'David', last_name: 'Miller', role: ROLES.ADMIN},
    {id: 6, email: 'olivia.wilson@example.com', first_name: 'Olivia', last_name: 'Wilson', role: ROLES.OBSERVER},
    {id: 7, email: 'daniel.anderson@example.com', first_name: 'Daniel', last_name: 'Anderson', role: ROLES.OPERATOR},
    {
        id: 8,
        email: 'matthew.taylor@example.com',
        first_name: 'Matthew',
        last_name: 'Taylor',
        role: ROLES.SECURITY_ADMIN,
    },
    {id: 9, email: 'sarah.brown@example.com', first_name: 'Sarah', last_name: 'Brown', role: ROLES.ADMIN},
    {id: 10, email: 'james.nelson@example.com', first_name: 'James', last_name: 'Nelson', role: ROLES.OBSERVER},
];
export const mockPOList = (request: MirageJs.Request): PaginationResult<PurchaseOrderListDTO> => ({
    content: [
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.REJECTED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.APPROVED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.CLOSED,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 'Sarah Smith',
            supplierName: 'Rose Inc.',
            supplierSiteId: 52156,
            supplierCode: 54219,
            status: PO_STATUS.PENDING,
            orderNo: 1234333,
            orderType: 'N/B',
            importCountry: 'China',
            countryOfSourcing: 'China',
            importBillToLoc: 5215,
            importBillToLocType: '-',
            routingLocation: '-',
            payMethod: 'MINT',
            poType: 'import',
            department: 5215124,
            promotion: 5215,
            orderCurrency: 'AED',
            orderExchangeRate: 9.99,
            pickupDate: new Date('04.04.2024').toISOString(),
            notAfterDate: new Date('04.04.2024').toISOString(),
            notBeforeDate: new Date('04.04.2024').toISOString(),
            orderApprovalDate: new Date('04.04.2024').toISOString(),
            otbEndOfWeekDate: new Date('04.04.2024').toISOString(),
            vendorOrdNo: 'BZ-2145125',
            landedCost: 12343,
            outstandingCost: 12343,
            canceledCost: 12343,
            backhaulType: '-',
            backhaulAllowance: 3123,
            duty: 5125,
            expenses: 5215,
            discount: 3,
            markupPercentRetail: 3,
            totalOrderRetailExcVAT: 33,
            totalOrderRetailIncVAT: 33,
            totalVAT: 333,
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

const mockPOItem: PurchaseOrderItemDTO = {
    id: 7165256,
    unitCostUOP: 50.75,
    itemType: 'Product',
    color: 'Blue',
    unitOfPurchase: 100,
    totalELCUOP: 5000.5,
    locationType: 'Warehouse',
    costSource: 'SupplierA',
    localCurrency: 'USD',
    unitELCUOP: 45.0,
    itemParent: 'ITEM_PARENT_ID', // или объект ItemDTO при необходимости
    currency: 'USD',
    itemDescription: 'High-quality steel screws',
    latestShipmentDate: '2024-12-23T00:00:00.000Z',
    estimatedInStockDate: '2024-01-23T00:00:00.000Z',
    itemGrandParent: 'ITEM_GRANDPARENT_ID',
    nonScaling: 'No',
    cancelledQtyUOP: 0,
    supplierUnitCost: 52.5,
    item: 'ITEM_001',
    locationName:
        'Shanghai Special Administrative Region "Penghai," Industrial Harbor Nantan, Plot No. 732, Huangpu River Coastal Strip, Berth 19, Longjiang Port Complex',
    quantity: 500,
    countryOfSourcing: 'China',
    size: 'Medium',
    variance: 0.5,
    vpn: 'vpn1',
    earliestShipmentDate: '2024-11-25T00:00:00.000Z',
    detailedColorDescription: 'Bright blue with a matte finish',
};

export const mockPOView: PurchaseOrderDTO = {
    id: 1234333,
    orderType: NO_DATA,
    importer: 1, // или объект ImporterDTO
    includeOnOrder: 'No',
    importOrder: 'Yes',
    estimatedRDCInStock: '2024-11-25T00:00:00.000Z',
    discount: 3,
    primaryCurrency: 'AED',
    totalOrderCost: null, // пока пусто, можно задать значения позже
    canceledCost: null, // пока пусто
    exchangeRate: 0.27,
    contact: '647584736',
    ediPO: 'No',
    poStatus: PO_STATUS.APPROVED,
    qcRequired: 'Yes',
    latestShipmentDate: '2024-12-15T00:00:00.000Z',
    supplierCode: 1425367, // или объект SupplierDTO
    supplierName: 'Rose Inc.',
    supplierSiteId: 1425367,
    otbEndOfWeekDate: '2024-12-27T00:00:00.000Z',
    orderNo: 123456,
    landedCost: 2000,
    orderCurrency: 'AED, USD',
    notAfterDate: '2024-12-31T00:00:00.000Z',
    notBeforeDate: '2024-11-01T00:00:00.000Z',
    importCountry: 'China',
    outstandingCost: 1500,
    locationPickUp: 'WH1',
    earliestShipDate: '2024-11-25T00:00:00.000Z',
    vendorOrdNo: 'BZ-123233',
    paymentTermsName: 'Net 30 Days',
    orderApprovalDate: '2024-11-24T00:00:00.000Z',
    location:
        'Shanghai Special Administrative Region "Penghai," Industrial Harbor Nantan, Plot No. 732, Huangpu River Coastal Strip, Berth 19, Longjiang Port Complex',
    poType: PO_TYPE.IMPORT,
    items: [mockPOItem],
    expenses: 50.0,
};

const UPLOAD_TYPE_NAME = {
    [UploadTypes.PO_UPLOAD]: 'PO Upload',
};

export const uploadedFileResponse: UploadDTO = {
    id: 123412,
    vendorOrderNo: '1421412',
    fileName: 'Table.csv',
    orderNo: 6,
    createdBy: 'Daniil Babichev',
    uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
    uploaded: '2024-11-01T09:00:00',
    errors: [],
    uploadRefNo: 5214,
    status: MASS_UPLOAD_STATUS.PENDING,
};

export const mockMUList = (request: MirageJs.Request): PaginationResult<UploadDTO> => ({
    content: [
        {
            id: 123412,
            vendorOrderNo: 'BZ-1234567',
            fileName: 'Report1.csv',
            orderNo: 123401,
            createdBy: 'Alice Johnson',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-01T09:00:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.PENDING,
        },
        {
            id: 123413,
            vendorOrderNo: 'BZ-2345678',
            fileName: 'Report2.csv',
            orderNo: 123402,
            createdBy: 'Bob Smith',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-02T10:30:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.ERROR,
        },
        {
            id: 123414,
            vendorOrderNo: 'BZ-3456789',
            fileName: 'Report3.csv',
            orderNo: 123403,
            createdBy: 'Charlie Brown',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-03T11:45:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 123415,
            vendorOrderNo: 'BZ-4567890',
            fileName: 'Report4.csv',
            orderNo: 123404,
            createdBy: 'Diana Prince',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-04T12:15:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.REJECTED,
        },
        {
            id: 1234176,
            vendorOrderNo: 'BZ-5678901',
            fileName: 'Report5.csv',
            orderNo: 123405,
            createdBy: 'Ethan Hunt',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-05T13:50:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 123417,
            vendorOrderNo: 'BZ-6789012',
            fileName: 'Report6.csv',
            orderNo: 123406,
            createdBy: 'Fiona Gallagher',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-06T14:20:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
        {
            id: 123418,
            vendorOrderNo: 'BZ-7890123',
            fileName: 'Report7.csv',
            orderNo: 123407,
            createdBy: 'George Costanza',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-07T15:00:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.REJECTED,
        },
        {
            id: 123419,
            vendorOrderNo: 'BZ-8901234',
            fileName: 'Report8.csv',
            orderNo: 123408,
            createdBy: 'Hannah Montana',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-08T16:30:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.ERROR,
        },
        {
            id: 123422,
            vendorOrderNo: 'BZ-9012345',
            fileName: 'Report9.csv',
            orderNo: 123409,
            createdBy: 'Ian Malcolm',
            uploadType: UPLOAD_TYPE_NAME[UploadTypes.PO_UPLOAD],
            uploaded: '2024-11-09T17:45:00',
            errors: [],
            uploadRefNo: 1234333,
            status: MASS_UPLOAD_STATUS.VALIDATED,
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

export const mockMUView: UploadDTO = {
    id: 1234333,
    uploadRefNo: 1234333,
    fileName: 'test.csv',
    orderNo: 12345678,
    vendorOrderNo: 'VENDOR123',
    uploadType: 'TYPE_A',
    createdBy: 'uploader1',
    uploaded: '2023-10-01T00:00:00Z',
    status: MASS_UPLOAD_STATUS.PENDING,
    errors: [
        {
            lineNumber: 1,
            columnName: 'COLUMN1',
            columnValue: 'VALUE1',
            errorMessage: 'Ошибка в значении',
        },
        {
            lineNumber: 2,
            columnName: 'COLUMN2',
            columnValue: 'VALUE2',
            errorMessage: 'Ошибка в значении',
        },
    ],
};
