import MirageJs from 'miragejs';

import {PaginationResult} from '@/app/components/PaginationTable/types';
import {UploadStatus, UploadTypes, UploadDTO} from '@/app/modules/mass-upload/types';
import {PO_STATUS, PurchaseOrderDTO} from '@/app/modules/purchase-orders/types';
import {AccountDTO, ROLES, UserDTO} from '@/store/account/types';

export const mockAccount: AccountDTO = {
    user: {
        id: 8008135,
        first_name: 'Alex',
        last_name: 'M',
        email: 'mail@example.com',
        role: ROLES.ADMIN,
    },
    access_token: '0000-0000',
    refresh_token: '0000-0000',
};

export const mockUsers: Array<UserDTO> = [
    {id: 1, email: 'john.doe@example.com', first_name: 'John', last_name: 'Doe', role: ROLES.ADMIN},
    {id: 2, email: 'jane.smith@example.com', first_name: 'Jane', last_name: 'Smith', role: ROLES.OBSERVER},
    {id: 3, email: 'michael.johnson@example.com', first_name: 'Michael', last_name: 'Johnson', role: ROLES.OPERATOR},
    {id: 4, email: 'emily.davis@example.com', first_name: 'Emily', last_name: 'Davis', role: ROLES.SECURITY_ADMIN},
    {id: 5, email: 'david.miller@example.com', first_name: 'David', last_name: 'Miller', role: ROLES.ADMIN},
    {id: 6, email: 'olivia.wilson@example.com', first_name: 'Olivia', last_name: 'Wilson', role: ROLES.OBSERVER},
    {id: 7, email: 'daniel.anderson@example.com', first_name: 'Daniel', last_name: 'Anderson', role: ROLES.OPERATOR},
    {
        id: 8,
        email: 'matthew.taylor@example.com',
        first_name: 'Matthew',
        last_name: 'Taylor',
        role: ROLES.SECURITY_ADMIN,
    },
    {id: 9, email: 'sarah.brown@example.com', first_name: 'Sarah', last_name: 'Brown', role: ROLES.ADMIN},
    {id: 10, email: 'james.nelson@example.com', first_name: 'James', last_name: 'Nelson', role: ROLES.OBSERVER},
];

export const mockPOList = (request: MirageJs.Request): PaginationResult<PurchaseOrderDTO> => ({
    content: [
        {
            id: 1234333,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.APPROVED,
            statusName: 'Approved',
            orderItems: 1244,
        },
        {
            id: 1234334,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.APPROVED,
            statusName: 'Approved',
            orderItems: 1244,
        },
        {
            id: 1234335,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.REJECTED,
            statusName: 'Rejected',
            orderItems: 1244,
        },
        {
            id: 1234336,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.PENDING,
            statusName: 'Pending',
            orderItems: 1244,
        },
        {
            id: 1234337,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.APPROVED,
            statusName: 'Approved',
            orderItems: 1244,
        },
        {
            id: 1234338,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.CLOSED,
            statusName: 'Closed',
            orderItems: 1244,
        },
        {
            id: 1234339,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.PENDING,
            statusName: 'Pending',
            orderItems: 1244,
        },
        {
            id: 1234340,
            totalOrderCost: 12543,
            raisedBy: 2116652,
            raisedByName: 'Sarah Smith',
            createdAt: new Date('04.04.2024').toISOString(),
            supplierId: 9812392,
            supplierName: 'Rose Inc.',
            supplierCountry: 'China',
            status: PO_STATUS.PENDING,
            statusName: 'Pending',
            orderItems: 1244,
        },
    ],
    totalElements: 10,
    totalPages: request.queryParams.size ? Math.ceil(10 / +request.queryParams.size) : 1,
});

export const uploadedFileResponse: UploadDTO = {
    vendorOrderNo: '1421412',
    fileName: 'Table.csv',
    orderNo: 6,
    createdBy: 'Daniil Babichev',
    uploadType: UploadTypes.PO_UPLOAD,
    errors: [],
    uploadRefNo: 5214,
    status: UploadStatus.PENDING,
};
